project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - "*.qmd"
    - "!code/day1/cSTM_3state_time.Rmd"
    - "!code/day1/cSTM_3state_tunnels.Rmd"
    - "!code/day1/decision_tree_HVE_solutions.Rmd"
    - "!code/day2/microsim_3-state_time.Rmd"
    - "!code/day3/cSTM_3state_SA_time.Rmd"
    - "!materials/intro_to_r/00_prep.Rmd"
    - "!materials/intro_to_r/01_getting_ready.Rmd"
    - "!materials/intro_to_r/02_Introduction_template.Rmd"
    - "!materials/intro_to_r/02_Introduction_solutions.Rmd"
    - "!materials/intro_to_r/03_data_manipulation_template.Rmd"
    - "!materials/intro_to_r/03_data_manipulation_solutions.Rmd"
    - "!materials/intro_to_r/04_plotting_template.Rmd"
    - "!materials/intro_to_r/04_plotting_solutions.Rmd"
    - "!materials/intro_to_r/05_loops_and_functions_template.Rmd"
    - "!materials/intro_to_r/05_loops_and_functions_solutions.Rmd"
    - "!materials/intro_to_r/Matrix algebra in R - template.Rmd.Rmd"
    - "!materials/intro_to_r/Matrix algebra in R - solutions.Rmd"
    - "!materials/intro_to_r/05_loops_and_functions_template.Rmd"
    - "!materials/intro_to_r/05_loops_and_functions_solutions.Rmd"

website:
  title: "Decision Modeling in R Workshop"
  site-url: "https://ppehli.github.io/DARTH_course/"
  repo-url: "https://github.com/ppehli/DARTH_course"
  search: true
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Pre-Workshop"
        href: prework/index.qmd
      - text: "Day 1"
        href: days/day1.qmd
      - text: "Day 2"
        href: days/day2.qmd
      - text: "Day 3"
        href: days/day3.qmd
      - text: "Resources"
        href: resources/index.qmd
  sidebar:
    style: "docked"
    contents:
      - section: "Home"
        contents:
          - index.qmd
          - Instructors.qmd
      - section: "Pre-Workshop Preparation"
        contents:
          - prework/index.qmd
          - prework/intro-r.qmd
          - prework/video-lectures-day1.qmd
          - prework/video-lectures-day2.qmd
          - prework/video-lectures-day3.qmd
      - section: "Workshop Days"
        contents:
          - days/day1.qmd
          - days/day2.qmd
          - days/day3.qmd
      - section: "Resources"
        contents:
          - resources/index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    number-sections: false
    code-copy: true
    code-overflow: wrap
    css: styles.css

execute:
  freeze: auto
