---
title: "Cost-Effectiveness and Decision Modeling using R"
subtitle: "Oslo, June 2026"
---

::: {.hero}
Welcome! This website is the official home for all information related to the Cost-Effectiveness and Decision Modeling workshop. This site contains all the information you’ll need to get the most out of this workshop, including software, R packages, and additional resources.
:::

## Workshop dates and location

In-person sessions will be taking place on the following dates from 10am-4pm GMT+2 (Oslo time):

- **June 25, 2026:** Decision trees and Markov models
- **June 26, 2026:** Microsimulation modeling
- **June 27, 2026:** Sensitivity analysis

The course will use Auditorium 2 on Floor 1 of the University of Oslo's main library building called Georg Sverdrups Hus. The address is: Moltke Moes vei 39, 0851 Oslo. Please click here for a link (available in Norwegian and English) to see a map of the building and transportation instructions: <https://www.uio.no/english/about/getting-around/areas/blindern/bl27/index.html>

## Expected workload

On workshop days, participants will spend approximately **5-6 hours in live interactive sessions**. We recommend investing an additional **2-4 hours per day** to review material and complete exercises.

## Suggested daily schedule

- Preparation modules with video lectures: **1-2 hours**
- Live interactive sessions with code demonstrations and coding exercises: **5-6 hours**
- Completion of coding assignments: **1-2 hours**

## Communication

Slack will be our main platform for communication for participants and instructors for this workshop. On course days, instructors will be quicker to respond on Slack than email. Please join Slack here: <https://darth-oslo2026.slack.com>

Prior to the course, if you have questions about preparation, installation, or access to materials, you can contact Petros and Alex:   

- `petros.pechlivanoglou@sickkids.ca`   
- `alexandra.moskalewicz@sickkids.ca`   

## What do I need to do before the workshop?

Everyone will need to complete the following items:

**1. Complete our pre-course survey**

Complete this Google Form so we can learn more about you: <https://docs.google.com/forms/d/e/1FAIpQLSc75SFT2TNL-xOU06_QeLgTGqW1_4yWYTlfXb2kLslfVBvBxA/viewform>

**2. Set up Slack**

We will use Slack as the main platform for online communications. Throughout and after the workshop, instructors and participants can stay connected on Slack to exchange ideas, discuss problems and seek help from each other.
Click here to join the Slack workspace: <https://darth-oslo2026.slack.com>. After you join, you can access the workspace via its URL or the Slack desktop app.

We encourage you to give us a short introduction about yourself in the main chatroom once you join!

**3. Install software**

In this workshop, we will use R and RStudio. Please install them on your machine prior to the start of the workshop.

If you will be using a company-issued computer to participate in the workshop, please work with your IT office to install R and RStudio on your computer as soon as possible.

If you will be using a personal machine, follow the installation instructions below:
- Download R from here and follow the installation procedure: <https://mirror.csclub.uwaterloo.ca/CRAN/>
- Then, download and install the free version of RStudio Desktop from here: <https://docs.posit.co/ide/user/#rstudio-ide-oss-downloads>

**4. Mandatory pre-course Intro to R module**

Prior to the start of the workshop, please go through the Introduction to R module to learn the fundamentals and functionality of R that you will need for the workshop. Depending on your current R skills, it may take you between **2-8 hours** to complete the module. Access the module here: <https://intro-to-r-mod.netlify.app/>

Please let Alex or Petros know if you encounter difficulties installing the *darthtools* and *dampack* R packages when completing the 00_prep.Rmd file on the first page of the module: <https://intro-to-r-mod.netlify.app/days/day1/getting_ready/>

**5. Familiarize yourself with this course website**

Please explore the website and locate the preparation materials (readings and video lectures) that should be viewed prior to attending the workshop each day.


