---
title: "Day 1: Decision Trees and Markov Models"
---

## Learning objectives

By the end of Day 1, participants should be able to:

- Understand how to organize R code for decision analytic modeling
- Implement a decision tree in R
- Implement a basic cohort state-transition model in R
- Understand how to calculate epidemiological and economic outcomes in a state-transition model
- Start understanding how to implement your own model in R

## Day 1 schedule

| Time | Material |
|---|---|
| 10:00am-10:15am | Workshop orientation / Introduction to model types
| 10:15am-11:00am | Structuring your R code / Decision trees in R
| 11:00am-12:00pm | Code walk through: cSTM 3-state model
| 12:00pm-12:30pm | Lunch
| 12:30pm-2:00pm  | Hands-on exercise: Code your own cSTM with sick-sicker example
| 2:00pm-3:00pm   | Incorporating time dependency in cSTM
| 3:00pm-4:00pm   | Exercise recap


## Materials for Morning Session

<a href="../slides/day1/26_DARTH_CourseIntroSlides.pptx" download>Download slides: Introduction to the course</a>   

<a href="../slides/day1/DecisionTreeExampleReview_HVE.pptx" download>Download slides: Decision Tree Modeling in R: Example</a>   

<a href="../slides/day1/CEA%20and%20Decision%20Modeling%20Overview_with%20Decision%20tree%20slides.pptx" download>Download slides: Cost-effectiveness and Decision Modeling</a>   

<a href="../code/day1/decision_tree_HVE_solutions.Rmd" download>Download demo code: Decision Trees</a> 

## Materials for Afternoon Session

<a href="../code/day1/cSTM_3state_time.Rmd" download>Download demo code: 3-state cSTM (simulation-time dependency)</a>   

<a href="../code/day1/cSTM_3state_tunnels.Rmd" download>Download demo code (tunnels): 3-state cSTM (state-residence time dependency)</a>   

### Exercise - cohort state-transition Sick-Sicker model   

<a href="../exercises/cSTM_sick-sicker_time_exercise_template.html" download>
  Download exercise handout
</a><br>

<a href="../data/HMD_USA_Mx.csv" download>
  Download lifetables
</a><br>

<a href="../exercises/cSTM_sick-sicker_time_exercise_template.Rmd" download>
  Download exercise template
</a>