---
title: "Day 3: Sensitivity Analysis"
---

## Learning objectives

By the end of Day 3, participants should be able to:

-   Make your model code into an R function
-   Implement deterministic and probabilistic sensitivity analyses in R
-   Visualize and interpret sensitivity analysis results in R

## Day 3 schedule

| Time | Material |
|------------------------------------|------------------------------------|
| 10:00am-10:30am | Review of Day 2 material |
| 10:30am-11:00am | Code walk-through: Deterministic sensitivity analysis with cSTM 3-state model |
| 11:00am-12:00pm | Code walk through: Probabilistic sensitivity analysis with cSTM 3-state model |
| 12:00pm-12:30pm | Lunch |
| 12:30pm-2:00pm | Hands-on exercise: Implement sensitivity analyses on cSTM with sick-sicker example |
| 2:00pm-4:00pm | Advanced topics - parameterizing decision models using published data |

## Materials for sensitivity analysis

<a href="../code/day3/cSTM_3state_SA_time.Rmd" download>Download demo code</a>

<a href="../code/day3/Functions_cSTM_3state_time.R" download>Download model function code</a>

<a href="../data/lifetable_rates.csv" download> Download data: "lifetable_rates.csv" </a><br>

### Exercise - Sensitivity analyses on the Markov Sick-Sicker model

<!-- <a href="../exercises/Functions_markov_sick-sicker_time_template.R" download> -->

<!--   Download Function -->

<!-- </a> -->

<a href="../exercises/markov_sick-sicker_time_SA_exercise_template.Rmd" download> Download exercise template </a>

<a href="../data/HMD_USA_Mx_2015.csv" download> Download data </a>

<a href="../exercises/Functions_markov_sick-sicker_time_template.R" download> Download model function </a>

<!-- ::: {#download-link-sa style="display:none;"}
<a href="../exercises/Functions_markov_sick-sicker_time.R" download> Download model function - SOLUTIONS </a>

<a href="../exercises/markov_sick-sicker_time_SA_solutions.Rmd" download> Download exercise - SOLUTIONS </a>
::: -->

## Materials for parameterizing decision models using published data

<a href="../slides/day3/survival_analysis.pdf" download>Download slides on survival analysis</a>

<a href="../slides/day3/parameterize_STM.pdf" download>Download slides on parameterizing decision models</a>

<a href="../code/day3/Section_2_TMB_demo.zip" download>Download demo code and folder structure as a zipped file</a>

<!-- ```{=html}
<script>
  const releaseTime = new Date("2026-06-27T16:00:00-04:00");
  const now = new Date();

  if (now >= releaseTime) {
    document.getElementById("download-link-sa").style.display = "block";
  }

</script>
``` -->
