---
title: "June 27: Sensitivity Analysis"
---

## Learning objectives

By the end of Day 3, participants should be able to:

- Make your model code into an R function
- Implement deterministic and probabilistic sensitivity analyses in R
- Visualize and interpret sensitivity analysis results in R

## Day 3 schedule

| Time | Material |
|---|---|
| 10:00am-10:30am | Review of Day 2 material
| 10:30am-11:00am | Code walk-through: Deterministic sensitivity analysis with cSTM 3-state model
| 11:00am-12:00pm | Code walk through: Probabilistic sensitivity analysis with cSTM 3-state model
| 12:00pm-12:30pm | Lunch
| 12:30pm-2:00pm  | Hands-on exercise: Implement sensitivity analyses on cSTM with sick-sicker example
| 2:00pm-4:00pm   | Advanced topics - TBD

## Materials

<!-- - [Download demo code](../code/day3/cSTM_3state_SA_time.Rmd)    -->

<!-- - [Download model function code](../code/day3/Functions_cSTM_3state_time.R) -->
<a href="../code/day3/cSTM_3state_SA_time.Rmd" download>Download demo code</a>   

<a href="../code/day3/Functions_cSTM_3state_time.R" download>Download model function code</a>   
<!-- - [Exercise 4 sensitivity analysis](../exercises/exercise-04-sensitivity-analysis.qmd) -->

### Exercise - Sensitivity analyses on the Markov Sick-Sicker model   

<!-- [Download Function](../exercises/exe4-Functions_markov_sick-sicker_time_template.R)    -->

<!-- [Download Dataset](../exercises/exe4-HMD_USA_Mx_2015.csv)    -->

<!-- [Download Exercise](../exercises/exe4-markov_sick-sicker_time_SA_exercise_template.Rmd)    -->

<a href="../exercises/exe4-Functions_markov_sick-sicker_time_template.R" download>
  Download Function
</a>

<a href="../exercises/exe4-HMD_USA_Mx_2015.csv" download>
  Download Dataset
</a>

<a href="../exercises/exe4-markov_sick-sicker_time_SA_exercise_template.Rmd" download>
  Download Exercise
</a>
<!-- - [Capstone exercise](../exercises/capstone.qmd) -->

<!-- ## Video lectures -->

<!-- **Right click below links and select “Open link in new tab”. -->

<!-- #### Sensitivity Analysis – Introduction    -->

<!-- <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/506091491?h=5e07e24203&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sensitivity Analysis - 00  Introduction"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script> -->

<!-- #### Sensitivity Analysis - 01 DSA    -->

<!-- <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/473705896?h=08aaee5604&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sensitivity Analysis - 01 DSA"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script> -->

<!-- #### Sensitivity Analysis - 02 PSA       -->

<!-- <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/473709355?h=7575dd9894&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sensitivity Analysis 02 - PSA"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script> -->


