---
title: "June 26: Microsimulation Modeling"
---

## Learning objectives

By the end of Day 2, participants should be able to:

- Understand implementation differences between microsimulation and cohort state transition models
- Understand how to summarize the output from a microsimulation model
- Understand how to incorporate more complex dependencies and dynamics in a microsimulation model
- Implement a microsimulation in R
- Understand how to convert a decision analytic model from an R script to an R function

## Day 2 schedule

| Time | Material |
|---|---|
| 10:00am-10:15am | Review of Day 1 material
| 10:15am-10:45am | Making your model a function: How and why
| 10:45am-12:00pm | Code walk through: Microsimulation 3-state model
| 12:00pm-12:30pm | Lunch
| 12:30pm-2:00pm  | Hands-on exercise: Code your own microsimulation model with Sick-Sicker example
| 2:00pm-4:00pm   | Advanced topics - TBD

## Materials

<!-- - [View slides: Microsimulation modeling in R](../slides/day2/Microsimulation_Slides.pdf) -->

<!-- - [R code demo & walkthrough - Make your model a function](../code/day2/Functions_cSTM_3state_time_demo.R) -->
<!-- - [R code demo & walkthrough - 3-state microsimulation](../code/day2/microsim_3-state_time.Rmd) -->
<a href="../slides/day2/Microsimulation_Slides.pdf" download>Download slides: Microsimulation modeling in R</a>   

<a href="../code/day2/Functions_cSTM_3state_time_demo.R" download>Download R code demo & walkthrough - Make your model a function</a>   

<a href="../code/day2/microsim_3-state_time.Rmd" download>Download R code demo & walkthrough - 3-state microsimulation</a>   
<!-- - [Exercise 3 - Sick-Sicker microsimulation with time dependency](../exercises/exercise-03-microsimulation.qmd) -->

### Exercise - Sick-Sicker microsimulation with time dependency   

<!-- [Download data: ‘mortProb_age.csv’](../exercises/exe3-mortProb_age.csv)    -->

<!-- [Download data: ‘MyPopulation-AgeDistribution.csv’](../exercises/exe3-MyPopulation-AgeDistribution.csv)    -->

<!-- [Download excercise template](../exercises/exe3-microsim_Sick-Sicker_time_exercise_template.Rmd)    -->

<a href="../exercises/exe3-mortProb_age.csv" download>
  Download data: ‘mortProb_age.csv’
</a><br>

<a href="../exercises/exe3-MyPopulation-AgeDistribution.csv" download>
  Download data: ‘MyPopulation-AgeDistribution.csv’
</a><br>

<a href="../exercises/exe3-microsim_Sick-Sicker_time_exercise_template.Rmd" download>
  Download exercise template
</a>

<!-- ## Video lectures -->

<!-- **Right click below links and select “Open link in new tab”. -->
<!-- #### Microsimulation - 1. Theory    -->

<!-- <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/473484372?h=b270d78171&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Microsimulation - 1. Theory"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script> -->


<!-- #### Microsimulation - 2. Efficiency    -->

<!-- <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/473071949?h=3491a03c0d&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Microsimulation - 2. Efficiency"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script> -->


<!-- #### Microsimulation - 3. Implementation    -->

<!-- <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/473414536?h=85887de382&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Microsimulation - 3. Implementation"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script> -->

<!-- #### Microsimulation - 4. State-residence    -->

<!-- <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/473464649?h=31c07bcb78&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Mircosimulation - 4. State-residence"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script> -->

## Readings

- Krijkamp EM, Alarid-Escudero F, Enns EA, Jalal HJ, Hunink MM, Pechlivanoglou P. *Microsimulation modeling for health decision sciences using R: A tutorial.* Medical Decision Making (2018).
  <https://doi.org/10.1177/0272989X18754513>

